services:
  leadbot-db-docker:
    image: postgres:16
    restart: always
    volumes:
      - ${PWD}/.leadbot-build/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=leadbot
      - POSTGRES_PASSWORD=leadbot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  leadbot-builder:
    build:
      context: .
      args:
        - SCOPE=builder
    depends_on:
      leadbot-db-docker:
        condition: service_healthy
    restart: always
    ports:
      - "8080:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env.docker
  leadbot-viewer:
    build:
      context: .
      args:
        - SCOPE=viewer
    depends_on:
      leadbot-db-docker:
        condition: service_healthy
    restart: always
    ports:
      - "8081:3000"
    env_file: .env.docker
