x-leadbot-common: &leadbot-common
  restart: always
  depends_on:
    leadbot-redis:
      condition: service_healthy
    leadbot-db:
      condition: service_healthy
  networks:
    - leadbot-network
  env_file: .env
  environment:
    REDIS_URL: redis://leadbot-redis:6379

services:
  leadbot-db:
    image: postgres:16
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=leadbot
      - POSTGRES_PASSWORD=leadbot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - leadbot-network

  leadbot-redis:
    image: redis:alpine
    restart: always
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-data:/data
    networks:
      - leadbot-network

  # Using Typebot base images until LeadBot custom images are built
  leadbot-builder:
    <<: *leadbot-common
    image: baptistearno/typebot-builder:latest
    ports:
      - "8080:3000"

  leadbot-viewer:
    <<: *leadbot-common
    image: baptistearno/typebot-viewer:latest
    ports:
      - "8081:3000"

networks:
  leadbot-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
